### ISSUE TITLE
Initial concept idea discussion

### ISSUE THREAD

**Issue by auryn-macmillan** [auryn-macmillan/DAOForum#1]
**Concepts paraphrased from Slock.it DAO Slack channel**

Purpose of this repo: To layout desired specification of a forum to be used for discussion of DAO proposals and other DAO related matters.

Initial ideas:
- Forum thread automatically created when a proposal is made by DAO holder.
  - Proposal creator has elevated status in thread, similar to reddit OP.
- Token controlled access/viewpoint for DAO holders.
- On chain or otherwise immutable threads/posts.
- Posts can be weighted/sorted by:
  - DAO stake
  - Reputation/web of trust (complicated, but boils down to number of users endorsing a particular user, number of users endorsing the endorser, and so on and so forth)
  - Time (newest first/last)
  - Up/down votes
  - Controversy (total votes up or down)

**Comment by vmichalik** [comment]
- Design: Something like a reddit/HN style design, open to other suggestions
  - Mobile-friendly interface
- Main page: A similar optional ranking style for proposals themselves, as well as the comments on proposals.
- Cloneable by DAO offshoots in case of a split

**Comment by vmichalik** [comment]
To discuss:
- Does it need moderation? (by election?)
- Should there be a lower limit on the required DAO ownership stake required to contribute?

**Comment by vmichalik** [comment]
- The plaintext proposals should be used and the smart contract code attached when available

**Comment by vmichalik** [comment]
- In the short term this could be web based for simplicity (with some thread hashes stored on the blockchain for posterity?) and eventually a Mist DApp

**Comment by FelixA** [comment]
further to discuss:
- Nestings (more than one layer, since there might exist multiple service providers)
- Incentivisation for moderation
- Some way to prevent spamming (on the long run - if there is a forum in which posts cannot be deleted by anyone else than by yourself there will be spam, so either there should be a minimum amount of tokens to be allowed to post, or spamming should cost s.th. For example by a button that marks posts as unnecessary.

**Comment by vmichalik** [comment]
Hopefully a feed based on stake/reputation should help, but raises barriers to entry and makes it a potential echo chamber

**Comment by auryn-macmillan** [comment]
ok, I'm going to go ahead and open up a few specific issues for each of the different categories ideas we're discussing here. I see a couple of broad categories:
1. Access control - usernames & password / Token controlled access / Some hybrid of the two
2. Moderation - How should moderation work? Should moderators exist? If so, how are mods chosen
3. Post/Thread sorting - Which sorting options are available and should be implemented
4. Spam control
5. Immutability / censorship resistance
6. Domain name ideas
